initializr:
  env:
    kotlin:
      default-version: "1.9.22"
  group-id:
    value: org.acme
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
          description: Servlet web application with Spring MVC and Tomcat
    - name: Innobase
      content:
        - name: ndyd-component-uc
          id: ndyd-component-uc
          groupId: com.ndyd
          artifactId: ndyd-component-uc
          scope: compile
          description: ndyd-component-uc.
          starter: false
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  javaVersions:
    - id: 17
      default: false
    - id: 11
      default: false
    - id: 1.8
      name: 8
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
